/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({...props}) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/src/components/three/globe/globeassets/PlanetRaw.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[5.78, -6.06, 3.51]}>
        <group
          position={[86.59, 24.07, -36.71]}
          rotation={[-1.84, -0.33, -1.41]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown"].geometry}
            material={nodes["tree-tree_crown"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk"].geometry}
            material={nodes["tree-tree_trunk"].material}
          />
        </group>
        <group
          position={[95.08, 20.14, -22.79]}
          rotation={[-1.84, -0.33, -1.41]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_1"].geometry}
            material={nodes["tree-tree_crown_1"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_1"].geometry}
            material={nodes["tree-tree_trunk_1"].material}
          />
        </group>
        <group
          position={[91.25, 34.78, -14.57]}
          rotation={[2.46, -0.02, -1.94]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_2"].geometry}
            material={nodes["tree-tree_crown_2"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_2"].geometry}
            material={nodes["tree-tree_trunk_2"].material}
          />
        </group>
        <group position={[-84.48, -30.64, 75.05]} rotation={[1.71, 0.22, 0.74]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_3"].geometry}
            material={nodes["tree-tree_trunk_3"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_3"].geometry}
            material={nodes["tree-tree_crown_3"].material}
          />
        </group>
        <group position={[-73.14, -19.33, 87.14]} rotation={[1.71, 0.22, 0.74]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_4"].geometry}
            material={nodes["tree-tree_trunk_4"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_4"].geometry}
            material={nodes["tree-tree_crown_4"].material}
          />
        </group>
        <group
          position={[-65.89, -31.65, 91.68]}
          rotation={[-2.66, -0.85, 1.68]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_5"].geometry}
            material={nodes["tree-tree_trunk_5"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_5"].geometry}
            material={nodes["tree-tree_crown_5"].material}
          />
        </group>
        <group position={[-76.38, -42.33, 82.57]} rotation={[1.77, 0.27, 0.73]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_6"].geometry}
            material={nodes["tree-tree_crown_6"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_6"].geometry}
            material={nodes["tree-tree_trunk_6"].material}
          />
        </group>
        <group position={[-95.08, -23.79, 64.17]} rotation={[1.73, 0.19, 1.15]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_7"].geometry}
            material={nodes["tree-tree_trunk_7"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_7"].geometry}
            material={nodes["tree-tree_crown_7"].material}
          />
        </group>
        <group position={[86.02, 38.6, -30.48]} rotation={[-1.83, -0.4, -1.4]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_8"].geometry}
            material={nodes["tree-tree_trunk_8"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_8"].geometry}
            material={nodes["tree-tree_crown_8"].material}
          />
        </group>
        <group position={[88.41, 12.3, -42.82]} rotation={[-0.24, 0.44, -1.3]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_9"].geometry}
            material={nodes["tree-tree_trunk_9"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_9"].geometry}
            material={nodes["tree-tree_crown_9"].material}
          />
        </group>
        <group position={[-45.28, 42.93, 94.41]} rotation={[1.15, -0.16, 0.38]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_10"].geometry}
            material={nodes["tree-tree_crown_10"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_10"].geometry}
            material={nodes["tree-tree_trunk_10"].material}
          />
        </group>
        <group position={[-31.03, 97.7, 14.44]} rotation={[0.05, -0.4, 0.04]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_11"].geometry}
            material={nodes["tree-tree_trunk_11"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_11"].geometry}
            material={nodes["tree-tree_crown_11"].material}
          />
        </group>
        <group position={[-36.13, 49.11, 95.36]} rotation={[1.17, -0.15, 0.31]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_12"].geometry}
            material={nodes["tree-tree_crown_12"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_12"].geometry}
            material={nodes["tree-tree_trunk_12"].material}
          />
        </group>
        <group position={[27.58, 48.89, 93.8]} rotation={[-1.8, -0.54, -2.58]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_13"].geometry}
            material={nodes["tree-tree_crown_13"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_13"].geometry}
            material={nodes["tree-tree_trunk_13"].material}
          />
        </group>
        <group
          position={[6.04, 16.98, -95.36]}
          rotation={[-1.55, -0.62, -0.25]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree1-tree_trunk"].geometry}
            material={nodes["tree1-tree_trunk"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree1-tree_crown"].geometry}
            material={nodes["tree1-tree_crown"].material}
          />
        </group>
        <group
          position={[-1.29, 25.5, -91.33]}
          rotation={[-1.55, -0.62, -0.25]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree1-tree_trunk_1"].geometry}
            material={nodes["tree1-tree_trunk_1"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree1-tree_crown_1"].geometry}
            material={nodes["tree1-tree_crown_1"].material}
          />
        </group>
        <group position={[-59.42, 23.32, -78.69]} rotation={[2.25, 0.09, 2.7]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree1-tree_trunk_2"].geometry}
            material={nodes["tree1-tree_trunk_2"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree1-tree_crown_2"].geometry}
            material={nodes["tree1-tree_crown_2"].material}
          />
        </group>
        <group position={[60.66, 81.22, 14.75]} rotation={[-1.9, -1.11, -1.74]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_14"].geometry}
            material={nodes["tree-tree_trunk_14"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_14"].geometry}
            material={nodes["tree-tree_crown_14"].material}
          />
        </group>
        <group position={[57.86, 80.53, 24.08]} rotation={[-1.94, -0.92, -2]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_15"].geometry}
            material={nodes["tree-tree_trunk_15"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_15"].geometry}
            material={nodes["tree-tree_crown_15"].material}
          />
        </group>
        <group
          position={[91.26, -51.31, -4.35]}
          rotation={[-0.77, 0.17, -1.66]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_16"].geometry}
            material={nodes["tree-tree_trunk_16"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_16"].geometry}
            material={nodes["tree-tree_crown_16"].material}
          />
        </group>
        <group
          position={[-3.55, -97.42, -40.22]}
          rotation={[-0.56, 1.38, -1.94]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_17"].geometry}
            material={nodes["tree-tree_trunk_17"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_17"].geometry}
            material={nodes["tree-tree_crown_17"].material}
          />
        </group>
        <group position={[8.36, -97.7, -39.43]} rotation={[-0.74, 1.2, -1.75]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree1-tree_trunk_3"].geometry}
            material={nodes["tree1-tree_trunk_3"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree1-tree_crown_3"].geometry}
            material={nodes["tree1-tree_crown_3"].material}
          />
        </group>
        <group
          position={[85.45, -58.29, -12.1]}
          rotation={[-0.75, 0.36, -1.66]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_trunk_18"].geometry}
            material={nodes["tree-tree_trunk_18"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree-tree_crown_18"].geometry}
            material={nodes["tree-tree_crown_18"].material}
          />
        </group>
        <group
          position={[40.96, 82.75, -17.2]}
          rotation={[-1.94, -0.92, -1.48]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree1-tree_trunk_4"].geometry}
            material={nodes["tree1-tree_trunk_4"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["tree1-tree_crown_4"].geometry}
            material={nodes["tree1-tree_crown_4"].material}
          />
        </group>
      </group>
      <group position={[0, -19.74, 13.32]}>
        <group position={[43.79, 46.66, 88.9]} rotation={[-1.8, -0.54, -2.58]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house-walls_house"].geometry}
            material={nodes["house-walls_house"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house-chimney_house,door"].geometry}
            material={nodes["house-chimney_house,door"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house-door_house"].geometry}
            material={nodes["house-door_house"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house-roof_house"].geometry}
            material={nodes["house-roof_house"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube1.geometry}
            material={nodes.Cube1.material}
            position={[0, 10.74, 5.43]}
          />
        </group>
        <group
          position={[73.89, 83.1, -22.32]}
          rotation={[-1.94, -0.92, -1.48]}
        >
          <group position={[11.65, -7.52, 0.19]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["door-door_house"].geometry}
              material={nodes["door-door_house"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["door-chimney_house,door"].geometry}
              material={nodes["door-chimney_house,door"].material}
            />
          </group>
          <group position={[-0.02, -4.51, 0.01]} rotation={[0, 1.57, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["windows-door_house"].geometry}
              material={nodes["windows-door_house"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["windows-chimney_house,door"].geometry}
              material={nodes["windows-chimney_house,door"].material}
            />
          </group>
          <group position={[5.96, 8.89, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["roof-roof_house2"].geometry}
              material={nodes["roof-roof_house2"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["roof-door_house"].geometry}
              material={nodes["roof-door_house"].material}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house2-walls_house2"].geometry}
            material={nodes["house2-walls_house2"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house2-roof_house2"].geometry}
            material={nodes["house2-roof_house2"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.chimney.geometry}
            material={nodes.chimney.material}
            position={[-3.79, 11.25, 5.43]}
          />
        </group>
        <group position={[-36.65, 68.42, -82.15]} rotation={[-1.08, 0.3, 0.46]}>
          <group position={[0, -3.57, -24.66]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["tree-tree_crown_19"].geometry}
              material={nodes["tree-tree_crown_19"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["tree-tree_trunk_19"].geometry}
              material={nodes["tree-tree_trunk_19"].material}
            />
          </group>
          <group position={[9.66, -6.23, 0.15]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["door-door_house_1"].geometry}
              material={nodes["door-door_house_1"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["door-chimney_house,door_1"].geometry}
              material={nodes["door-chimney_house,door_1"].material}
            />
          </group>
          <group position={[-0.01, -3.74, 0.01]} rotation={[0, 1.57, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["windows-door_house_1"].geometry}
              material={nodes["windows-door_house_1"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["windows-chimney_house,door_1"].geometry}
              material={nodes["windows-chimney_house,door_1"].material}
            />
          </group>
          <group position={[4.94, 7.37, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["roof-roof_house2_1"].geometry}
              material={nodes["roof-roof_house2_1"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["roof-door_house_1"].geometry}
              material={nodes["roof-door_house_1"].material}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house5-walls_house2"].geometry}
            material={nodes["house5-walls_house2"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house5-roof_house2"].geometry}
            material={nodes["house5-roof_house2"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.chimney_1.geometry}
            material={nodes.chimney_1.material}
            position={[-3.14, 9.32, 4.5]}
          />
        </group>
        <group
          position={[41.67, -80.88, -44.52]}
          rotation={[-0.74, 1.2, -1.75]}
        >
          <group position={[11.65, -5.85, 0.19]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["door-door_house_2"].geometry}
              material={nodes["door-door_house_2"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["door-chimney_house,door_2"].geometry}
              material={nodes["door-chimney_house,door_2"].material}
            />
          </group>
          <group position={[-0.02, -2.85, 0.01]} rotation={[0, 1.57, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["windows-door_house_2"].geometry}
              material={nodes["windows-door_house_2"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["windows-chimney_house,door_2"].geometry}
              material={nodes["windows-chimney_house,door_2"].material}
            />
          </group>
          <group position={[5.96, 10.56, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["roof-roof_house2_2"].geometry}
              material={nodes["roof-roof_house2_2"].material}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes["roof-door_house_2"].geometry}
              material={nodes["roof-door_house_2"].material}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.chimney_2.geometry}
            material={nodes.chimney_2.material}
            position={[-3.79, 12.92, 5.43]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house1-walls_house2"].geometry}
            material={nodes["house1-walls_house2"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house1-roof_house2"].geometry}
            material={nodes["house1-roof_house2"].material}
          />
        </group>
        <group position={[-39.1, 37.76, 92.71]} rotation={[1.3, -0.09, 0.4]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house3-chimney_house,door"].geometry}
            material={nodes["house3-chimney_house,door"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house3-chimney_house,door_1"].geometry}
            material={nodes["house3-chimney_house,door_1"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house3-door_house"].geometry}
            material={nodes["house3-door_house"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house3-roof_house"].geometry}
            material={nodes["house3-roof_house"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house3-walls_house"].geometry}
            material={nodes["house3-walls_house"].material}
          />
        </group>
        <group
          position={[103.02, -23.39, 0.94]}
          rotation={[-0.77, 0.17, -1.66]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house6-chimney_house,door"].geometry}
            material={nodes["house6-chimney_house,door"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house6-chimney_house,door_1"].geometry}
            material={nodes["house6-chimney_house,door_1"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house6-door_house"].geometry}
            material={nodes["house6-door_house"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house6-roof_house"].geometry}
            material={nodes["house6-roof_house"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house6-walls_house"].geometry}
            material={nodes["house6-walls_house"].material}
          />
        </group>
        <group
          position={[-103.02, 10.15, -31.84]}
          rotation={[-1.98, 0.16, 1.4]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house4-chimney_house,door"].geometry}
            material={nodes["house4-chimney_house,door"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house4-chimney_house,door_1"].geometry}
            material={nodes["house4-chimney_house,door_1"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house4-door_house"].geometry}
            material={nodes["house4-door_house"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house4-roof_house"].geometry}
            material={nodes["house4-roof_house"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house4-walls_house"].geometry}
            material={nodes["house4-walls_house"].material}
          />
        </group>
        <group position={[-53.88, 1.32, -96.05]} rotation={[-1.98, 0.16, 0.46]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house7-chimney_house,door"].geometry}
            material={nodes["house7-chimney_house,door"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house7-chimney_house,door_1"].geometry}
            material={nodes["house7-chimney_house,door_1"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house7-door_house"].geometry}
            material={nodes["house7-door_house"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house7-roof_house"].geometry}
            material={nodes["house7-roof_house"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["house7-walls_house"].geometry}
            material={nodes["house7-walls_house"].material}
          />
        </group>
      </group>
      <group position={[12.34, 26.18, -13.34]}>
        <group position={[-76.95, 63.79, 52.06]} rotation={[0.16, 0.11, 0.62]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["building01-chimney_house,door"].geometry}
            material={nodes["building01-chimney_house,door"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["building01-water"].geometry}
            material={nodes["building01-water"].material}
          />
        </group>
        <group position={[-12.01, 86.04, 2.98]} rotation={[-0.16, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["building03-stones"].geometry}
            material={nodes["building03-stones"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["building03-water"].geometry}
            material={nodes["building03-water"].material}
          />
        </group>
        <group position={[-30.6, 48.5, 96.44]} rotation={[0.73, -0.29, 0.16]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["building021-walls_house2"].geometry}
            material={nodes["building021-walls_house2"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["building021-water"].geometry}
            material={nodes["building021-water"].material}
          />
        </group>
        <group
          position={[42.82, -86.04, -58.23]}
          rotation={[-2.21, -0.35, -0.57]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["building02-water"].geometry}
            material={nodes["building02-water"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["building02-walls_house2"].geometry}
            material={nodes["building02-walls_house2"].material}
          />
        </group>
        <group
          position={[76.95, -18.94, -58.87]}
          rotation={[-1.83, -0.4, -0.99]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["building03-water_1"].geometry}
            material={nodes["building03-water_1"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["building03-stones_1"].geometry}
            material={nodes["building03-stones_1"].material}
          />
        </group>
        <group
          position={[13.32, -26.61, -96.44]}
          rotation={[-1.55, -0.62, -0.25]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["building011-water"].geometry}
            material={nodes["building011-water"].material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes["building011-chimney_house,door"].geometry}
            material={nodes["building011-chimney_house,door"].material}
          />
        </group>
      </group>
      <group position={[22.8, -27.03, 43.41]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stones3.geometry}
          material={nodes.stones3.material}
          position={[66.48, 29.6, -66.37]}
          rotation={[-2.57, 0.63, -0.2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stones_1.geometry}
          material={nodes.stones_1.material}
          position={[-37.01, -2.05, 66.37]}
          rotation={[1.06, 0.16, -2.95]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stones3_1.geometry}
          material={nodes.stones3_1.material}
          position={[9.89, -29.6, 51.96]}
          rotation={[0.28, 0, 0.38]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stones2.geometry}
          material={nodes.stones2.material}
          position={[-66.48, -28.88, 43.96]}
          rotation={[1.02, 0.35, -2.94]}
        />
      </group>
      <group position={[-3.25, -4.48, 12.97]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.road_1.geometry}
          material={nodes.road_1.material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["road-roof_house"].geometry}
          material={nodes["road-roof_house"].material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["road-background,floor"].geometry}
          material={materials["background,floor"]}
        />
      </group>
      <group position={[-0.42, -10.99, 10.29]} rotation={[1.01, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["planet-planet"].geometry}
          material={materials.planet}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["planet-water"].geometry}
          material={nodes["planet-water"].material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/planet.gltf");