/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";
import { useFrame } from "@react-three/fiber";
import { DITUMesh } from "../../../../datamodels/Models";

type GLTFResult = GLTF & {
  nodes: {
    ["tree-tree_crown"]: THREE.Mesh;
    ["tree-tree_trunk"]: THREE.Mesh;
    ["tree-tree_crown_1"]: THREE.Mesh;
    ["tree-tree_trunk_1"]: THREE.Mesh;
    ["tree-tree_crown_2"]: THREE.Mesh;
    ["tree-tree_trunk_2"]: THREE.Mesh;
    ["tree-tree_trunk_3"]: THREE.Mesh;
    ["tree-tree_crown_3"]: THREE.Mesh;
    ["tree-tree_trunk_4"]: THREE.Mesh;
    ["tree-tree_crown_4"]: THREE.Mesh;
    ["tree-tree_trunk_5"]: THREE.Mesh;
    ["tree-tree_crown_5"]: THREE.Mesh;
    ["tree-tree_crown_6"]: THREE.Mesh;
    ["tree-tree_trunk_6"]: THREE.Mesh;
    ["tree-tree_trunk_7"]: THREE.Mesh;
    ["tree-tree_crown_7"]: THREE.Mesh;
    ["tree-tree_trunk_8"]: THREE.Mesh;
    ["tree-tree_crown_8"]: THREE.Mesh;
    ["tree-tree_trunk_9"]: THREE.Mesh;
    ["tree-tree_crown_9"]: THREE.Mesh;
    ["tree-tree_crown_10"]: THREE.Mesh;
    ["tree-tree_trunk_10"]: THREE.Mesh;
    ["tree-tree_trunk_11"]: THREE.Mesh;
    ["tree-tree_crown_11"]: THREE.Mesh;
    ["tree-tree_crown_12"]: THREE.Mesh;
    ["tree-tree_trunk_12"]: THREE.Mesh;
    ["tree-tree_crown_13"]: THREE.Mesh;
    ["tree-tree_trunk_13"]: THREE.Mesh;
    ["tree1-tree_trunk"]: THREE.Mesh;
    ["tree1-tree_crown"]: THREE.Mesh;
    ["tree1-tree_trunk_1"]: THREE.Mesh;
    ["tree1-tree_crown_1"]: THREE.Mesh;
    ["tree1-tree_trunk_2"]: THREE.Mesh;
    ["tree1-tree_crown_2"]: THREE.Mesh;
    ["tree-tree_trunk_14"]: THREE.Mesh;
    ["tree-tree_crown_14"]: THREE.Mesh;
    ["tree-tree_trunk_15"]: THREE.Mesh;
    ["tree-tree_crown_15"]: THREE.Mesh;
    ["tree-tree_trunk_16"]: THREE.Mesh;
    ["tree-tree_crown_16"]: THREE.Mesh;
    ["tree-tree_trunk_17"]: THREE.Mesh;
    ["tree-tree_crown_17"]: THREE.Mesh;
    ["tree1-tree_trunk_3"]: THREE.Mesh;
    ["tree1-tree_crown_3"]: THREE.Mesh;
    ["tree-tree_trunk_18"]: THREE.Mesh;
    ["tree-tree_crown_18"]: THREE.Mesh;
    ["tree1-tree_trunk_4"]: THREE.Mesh;
    ["tree1-tree_crown_4"]: THREE.Mesh;
    ["house-walls_house"]: THREE.Mesh;
    ["house-chimney_house,door"]: THREE.Mesh;
    ["house-door_house"]: THREE.Mesh;
    ["house-roof_house"]: THREE.Mesh;
    Cube1: THREE.Mesh;
    ["door-door_house"]: THREE.Mesh;
    ["door-chimney_house,door"]: THREE.Mesh;
    ["windows-door_house"]: THREE.Mesh;
    ["windows-chimney_house,door"]: THREE.Mesh;
    ["roof-roof_house2"]: THREE.Mesh;
    ["roof-door_house"]: THREE.Mesh;
    ["house2-walls_house2"]: THREE.Mesh;
    ["house2-roof_house2"]: THREE.Mesh;
    chimney: THREE.Mesh;
    ["tree-tree_crown_19"]: THREE.Mesh;
    ["tree-tree_trunk_19"]: THREE.Mesh;
    ["door-door_house_1"]: THREE.Mesh;
    ["door-chimney_house,door_1"]: THREE.Mesh;
    ["windows-door_house_1"]: THREE.Mesh;
    ["windows-chimney_house,door_1"]: THREE.Mesh;
    ["roof-roof_house2_1"]: THREE.Mesh;
    ["roof-door_house_1"]: THREE.Mesh;
    ["house5-walls_house2"]: THREE.Mesh;
    ["house5-roof_house2"]: THREE.Mesh;
    chimney_1: THREE.Mesh;
    ["door-door_house_2"]: THREE.Mesh;
    ["door-chimney_house,door_2"]: THREE.Mesh;
    ["windows-door_house_2"]: THREE.Mesh;
    ["windows-chimney_house,door_2"]: THREE.Mesh;
    ["roof-roof_house2_2"]: THREE.Mesh;
    ["roof-door_house_2"]: THREE.Mesh;
    chimney_2: THREE.Mesh;
    ["house1-walls_house2"]: THREE.Mesh;
    ["house1-roof_house2"]: THREE.Mesh;
    ["house3-chimney_house,door"]: THREE.Mesh;
    ["house3-chimney_house,door_1"]: THREE.Mesh;
    ["house3-door_house"]: THREE.Mesh;
    ["house3-roof_house"]: THREE.Mesh;
    ["house3-walls_house"]: THREE.Mesh;
    ["house6-chimney_house,door"]: THREE.Mesh;
    ["house6-chimney_house,door_1"]: THREE.Mesh;
    ["house6-door_house"]: THREE.Mesh;
    ["house6-roof_house"]: THREE.Mesh;
    ["house6-walls_house"]: THREE.Mesh;
    ["house4-chimney_house,door"]: THREE.Mesh;
    ["house4-chimney_house,door_1"]: THREE.Mesh;
    ["house4-door_house"]: THREE.Mesh;
    ["house4-roof_house"]: THREE.Mesh;
    ["house4-walls_house"]: THREE.Mesh;
    ["house7-chimney_house,door"]: THREE.Mesh;
    ["house7-chimney_house,door_1"]: THREE.Mesh;
    ["house7-door_house"]: THREE.Mesh;
    ["house7-roof_house"]: THREE.Mesh;
    ["house7-walls_house"]: THREE.Mesh;
    ["building01-chimney_house,door"]: THREE.Mesh;
    ["building01-water"]: THREE.Mesh;
    ["building03-stones"]: THREE.Mesh;
    ["building03-water"]: THREE.Mesh;
    ["building021-walls_house2"]: THREE.Mesh;
    ["building021-water"]: THREE.Mesh;
    ["building02-water"]: THREE.Mesh;
    ["building02-walls_house2"]: THREE.Mesh;
    ["building03-water_1"]: THREE.Mesh;
    ["building03-stones_1"]: THREE.Mesh;
    ["building011-water"]: THREE.Mesh;
    ["building011-chimney_house,door"]: THREE.Mesh;
    stones3: THREE.Mesh;
    stones_1: THREE.Mesh;
    stones3_1: THREE.Mesh;
    stones2: THREE.Mesh;
    road_1: THREE.Mesh;
    ["road-roof_house"]: THREE.Mesh;
    ["road-background,floor"]: THREE.Mesh;
    ["planet-planet"]: THREE.Mesh;
    ["planet-water"]: THREE.Mesh;
  };
  materials: {
    ["tree crown"]: THREE.MeshStandardMaterial;
    ["tree trunk"]: THREE.MeshStandardMaterial;
    ["walls house"]: THREE.MeshStandardMaterial;
    ["chimney house,door"]: THREE.MeshStandardMaterial;
    ["door house"]: THREE.MeshStandardMaterial;
    ["roof house"]: THREE.MeshStandardMaterial;
    ["door house"]: THREE.MeshStandardMaterial;
    ["chimney house,door"]: THREE.MeshStandardMaterial;
    ["roof house2"]: THREE.MeshStandardMaterial;
    ["walls house2"]: THREE.MeshStandardMaterial;
    water: THREE.MeshStandardMaterial;
    stones: THREE.MeshStandardMaterial;
    water: THREE.MeshStandardMaterial;
    ["walls house2"]: THREE.MeshStandardMaterial;
    ["roof house"]: THREE.MeshStandardMaterial;
    ["background,floor"]: THREE.MeshStandardMaterial;
    planet: THREE.MeshStandardMaterial;
  };
};

const defaultLocation = "/src/components/three/globe/globeassets/PlanetRaw.gltf"
const numImplemented = 2; // How many houses have the appropriate props


export default function Planet({rotationSpeed, state, ...props}: {rotationSpeed: number, state: React.MutableRefObject<DITUMesh[]>, props?: JSX.IntrinsicElements["group"]}) {
  const wholePlanet = useRef(null);
  const allHouses = useRef(null);

  const __registerRef = function (id: number ) {
    return (r: THREE.Group | null) => {
      if (!r || !state.current[id]) {return}
      state.current[id].ref = r ?? undefined
    }
  }
  
   // Don't know why types don't like each other :)
   // @ts-ignore
  const { nodes, materials } = useGLTF(defaultLocation) as GLTFResult;

  useFrame((state, delta, xrFrame) => {
    if (wholePlanet.current) {
      wholePlanet.current.rotation.y += delta * rotationSpeed // spin the globe
    }
  });

  return (
    <group ref={wholePlanet} {...props} dispose={null}>
      <group>
        <group name="Low_Poly_Planet" userData={{ name: "Low Poly Planet" }}>
          <group /* Trees */
            name="trees"
            position={[5.7822356, -6.0569577, 3.5139358]}
            rotation={[0, -1e-7, -1e-7]}
            userData={{ name: "trees" }}
          >
            <group
              name="tree"
              position={[86.5854721, 24.0708561, -36.7069702]}
              rotation={[-1.8373578, -0.331273, -1.4082724]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_crown"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown"].geometry}
                material={nodes["tree-tree_crown"].material}
                userData={{ name: "tree-tree crown" }}
              />
              <mesh
                name="tree-tree_trunk"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk"].geometry}
                material={nodes["tree-tree_trunk"].material}
                userData={{ name: "tree-tree trunk" }}
              />
            </group>
            <group
              name="tree_1"
              position={[95.0759506, 20.1443844, -22.7927666]}
              rotation={[-1.8373578, -0.331273, -1.4082724]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_crown_1"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_1"].geometry}
                material={nodes["tree-tree_crown_1"].material}
                userData={{ name: "tree-tree crown" }}
              />
              <mesh
                name="tree-tree_trunk_1"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_1"].geometry}
                material={nodes["tree-tree_trunk_1"].material}
                userData={{ name: "tree-tree trunk" }}
              />
            </group>
            <group
              name="tree_2"
              position={[91.2483063, 34.7800903, -14.5691481]}
              rotation={[2.4560029, -0.0184512, -1.9380236]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_crown_2"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_2"].geometry}
                material={nodes["tree-tree_crown_2"].material}
                userData={{ name: "tree-tree crown" }}
              />
              <mesh
                name="tree-tree_trunk_2"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_2"].geometry}
                material={nodes["tree-tree_trunk_2"].material}
                userData={{ name: "tree-tree trunk" }}
              />
            </group>
            <group
              name="tree_3"
              position={[-84.4828644, -30.6374664, 75.0522995]}
              rotation={[1.7132249, 0.2203227, 0.7377949]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_trunk_3"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_3"].geometry}
                material={nodes["tree-tree_trunk_3"].material}
                userData={{ name: "tree-tree trunk" }}
              />
              <mesh
                name="tree-tree_crown_3"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_3"].geometry}
                material={nodes["tree-tree_crown_3"].material}
                userData={{ name: "tree-tree crown" }}
              />
            </group>
            <group
              name="tree_4"
              position={[-73.141304, -19.3335266, 87.1384048]}
              rotation={[1.7132249, 0.2203227, 0.7377949]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_trunk_4"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_4"].geometry}
                material={nodes["tree-tree_trunk_4"].material}
                userData={{ name: "tree-tree trunk" }}
              />
              <mesh
                name="tree-tree_crown_4"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_4"].geometry}
                material={nodes["tree-tree_crown_4"].material}
                userData={{ name: "tree-tree crown" }}
              />
            </group>
            <group
              name="tree_5"
              position={[-65.8932037, -31.6504116, 91.6769333]}
              rotation={[-2.6596809, -0.8496523, 1.678795]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_trunk_5"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_5"].geometry}
                material={nodes["tree-tree_trunk_5"].material}
                userData={{ name: "tree-tree trunk" }}
              />
              <mesh
                name="tree-tree_crown_5"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_5"].geometry}
                material={nodes["tree-tree_crown_5"].material}
                userData={{ name: "tree-tree crown" }}
              />
            </group>
            <group
              name="tree_6"
              position={[-76.3802567, -42.3270798, 82.5654526]}
              rotation={[1.7656526, 0.2660112, 0.7251654]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_crown_6"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_6"].geometry}
                material={nodes["tree-tree_crown_6"].material}
                userData={{ name: "tree-tree crown" }}
              />
              <mesh
                name="tree-tree_trunk_6"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_6"].geometry}
                material={nodes["tree-tree_trunk_6"].material}
                userData={{ name: "tree-tree trunk" }}
              />
            </group>
            <group
              name="tree_7"
              position={[-95.0759506, -23.7868404, 64.1669769]}
              rotation={[1.7290106, 0.1872915, 1.1489599]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_trunk_7"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_7"].geometry}
                material={nodes["tree-tree_trunk_7"].material}
                userData={{ name: "tree-tree trunk" }}
              />
              <mesh
                name="tree-tree_crown_7"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_7"].geometry}
                material={nodes["tree-tree_crown_7"].material}
                userData={{ name: "tree-tree crown" }}
              />
            </group>
            <group
              name="tree_8"
              position={[86.0189819, 38.5970039, -30.4775867]}
              rotation={[-1.82536, -0.3987315, -1.4039873]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_trunk_8"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_8"].geometry}
                material={nodes["tree-tree_trunk_8"].material}
                userData={{ name: "tree-tree trunk" }}
              />
              <mesh
                name="tree-tree_crown_8"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_8"].geometry}
                material={nodes["tree-tree_crown_8"].material}
                userData={{ name: "tree-tree crown" }}
              />
            </group>
            <group
              name="tree_9"
              position={[88.4137955, 12.2996216, -42.8179817]}
              rotation={[-0.2379739, 0.4435501, -1.3001455]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_trunk_9"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_9"].geometry}
                material={nodes["tree-tree_trunk_9"].material}
                userData={{ name: "tree-tree trunk" }}
              />
              <mesh
                name="tree-tree_crown_9"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_9"].geometry}
                material={nodes["tree-tree_crown_9"].material}
                userData={{ name: "tree-tree crown" }}
              />
            </group>
            <group
              name="tree_10"
              position={[-45.2842407, 42.9278793, 94.4066544]}
              rotation={[1.1489851, -0.155968, 0.3769722]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_crown_10"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_10"].geometry}
                material={nodes["tree-tree_crown_10"].material}
                userData={{ name: "tree-tree crown" }}
              />
              <mesh
                name="tree-tree_trunk_10"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_10"].geometry}
                material={nodes["tree-tree_trunk_10"].material}
                userData={{ name: "tree-tree trunk" }}
              />
            </group>
            <group
              name="tree_11"
              position={[-31.0305309, 97.701416, 14.4380436]}
              rotation={[0.0522668, -0.4047104, 0.0395572]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_trunk_11"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_11"].geometry}
                material={nodes["tree-tree_trunk_11"].material}
                userData={{ name: "tree-tree trunk" }}
              />
              <mesh
                name="tree-tree_crown_11"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_11"].geometry}
                material={nodes["tree-tree_crown_11"].material}
                userData={{ name: "tree-tree crown" }}
              />
            </group>
            <group
              name="tree_12"
              position={[-36.1255455, 49.114315, 95.3607407]}
              rotation={[1.1684785, -0.1483064, 0.3141363]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_crown_12"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_12"].geometry}
                material={nodes["tree-tree_crown_12"].material}
                userData={{ name: "tree-tree crown" }}
              />
              <mesh
                name="tree-tree_trunk_12"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_12"].geometry}
                material={nodes["tree-tree_trunk_12"].material}
                userData={{ name: "tree-tree trunk" }}
              />
            </group>
            <group
              name="tree_13"
              position={[27.5828953, 48.8881378, 93.7962341]}
              rotation={[-1.7954383, -0.5447743, -2.5780792]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_crown_13"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_13"].geometry}
                material={nodes["tree-tree_crown_13"].material}
                userData={{ name: "tree-tree crown" }}
              />
              <mesh
                name="tree-tree_trunk_13"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_13"].geometry}
                material={nodes["tree-tree_trunk_13"].material}
                userData={{ name: "tree-tree trunk" }}
              />
            </group>
            <group
              name="tree1"
              position={[6.0382214, 16.9787807, -95.3607407]}
              rotation={[-1.5537167, -0.6180533, -0.2498459]}
              userData={{ name: "tree.1" }}
            >
              <mesh
                name="tree1-tree_trunk"
                castShadow
                receiveShadow
                geometry={nodes["tree1-tree_trunk"].geometry}
                material={nodes["tree1-tree_trunk"].material}
                userData={{ name: "tree.1-tree trunk" }}
              />
              <mesh
                name="tree1-tree_crown"
                castShadow
                receiveShadow
                geometry={nodes["tree1-tree_crown"].geometry}
                material={nodes["tree1-tree_crown"].material}
                userData={{ name: "tree.1-tree crown" }}
              />
            </group>
            <group
              name="tree1_1"
              position={[-1.2850014, 25.4993458, -91.3269577]}
              rotation={[-1.5537167, -0.6180533, -0.2498459]}
              userData={{ name: "tree.1" }}
            >
              <mesh
                name="tree1-tree_trunk_1"
                castShadow
                receiveShadow
                geometry={nodes["tree1-tree_trunk_1"].geometry}
                material={nodes["tree1-tree_trunk_1"].material}
                userData={{ name: "tree.1-tree trunk" }}
              />
              <mesh
                name="tree1-tree_crown_1"
                castShadow
                receiveShadow
                geometry={nodes["tree1-tree_crown_1"].geometry}
                material={nodes["tree1-tree_crown_1"].material}
                userData={{ name: "tree.1-tree crown" }}
              />
            </group>
            <group
              name="tree1_2"
              position={[-59.4220314, 23.32337, -78.687973]}
              rotation={[2.2546328, 0.094585, 2.7014651]}
              userData={{ name: "tree.1" }}
            >
              <mesh
                name="tree1-tree_trunk_2"
                castShadow
                receiveShadow
                geometry={nodes["tree1-tree_trunk_2"].geometry}
                material={nodes["tree1-tree_trunk_2"].material}
                userData={{ name: "tree.1-tree trunk" }}
              />
              <mesh
                name="tree1-tree_crown_2"
                castShadow
                receiveShadow
                geometry={nodes["tree1-tree_crown_2"].geometry}
                material={nodes["tree1-tree_crown_2"].material}
                userData={{ name: "tree.1-tree crown" }}
              />
            </group>
            <group
              name="tree_14"
              position={[60.6643829, 81.2188339, 14.7509861]}
              rotation={[-1.9042008, -1.1077893, -1.7425747]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_trunk_14"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_14"].geometry}
                material={nodes["tree-tree_trunk_14"].material}
                userData={{ name: "tree-tree trunk" }}
              />
              <mesh
                name="tree-tree_crown_14"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_14"].geometry}
                material={nodes["tree-tree_crown_14"].material}
                userData={{ name: "tree-tree crown" }}
              />
            </group>
            <group
              name="tree_15"
              position={[57.8638687, 80.5264969, 24.0756626]}
              rotation={[-1.9420455, -0.9191507, -1.9962281]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_trunk_15"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_15"].geometry}
                material={nodes["tree-tree_trunk_15"].material}
                userData={{ name: "tree-tree trunk" }}
              />
              <mesh
                name="tree-tree_crown_15"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_15"].geometry}
                material={nodes["tree-tree_crown_15"].material}
                userData={{ name: "tree-tree crown" }}
              />
            </group>
            <group
              name="tree_16"
              position={[91.2553482, -51.3060417, -4.3507032]}
              rotation={[-0.7657917, 0.1666034, -1.6556023]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_trunk_16"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_16"].geometry}
                material={nodes["tree-tree_trunk_16"].material}
                userData={{ name: "tree-tree trunk" }}
              />
              <mesh
                name="tree-tree_crown_16"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_16"].geometry}
                material={nodes["tree-tree_crown_16"].material}
                userData={{ name: "tree-tree crown" }}
              />
            </group>
            <group
              name="tree_17"
              position={[-3.5477331, -97.4248428, -40.2151146]}
              rotation={[-0.5560714, 1.3838932, -1.9351155]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_trunk_17"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_17"].geometry}
                material={nodes["tree-tree_trunk_17"].material}
                userData={{ name: "tree-tree trunk" }}
              />
              <mesh
                name="tree-tree_crown_17"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_17"].geometry}
                material={nodes["tree-tree_crown_17"].material}
                userData={{ name: "tree-tree crown" }}
              />
            </group>
            <group
              name="tree1_3"
              position={[8.3608456, -97.701416, -39.4307671]}
              rotation={[-0.742796, 1.200526, -1.7547974]}
              userData={{ name: "tree.1" }}
            >
              <mesh
                name="tree1-tree_trunk_3"
                castShadow
                receiveShadow
                geometry={nodes["tree1-tree_trunk_3"].geometry}
                material={nodes["tree1-tree_trunk_3"].material}
                userData={{ name: "tree.1-tree trunk" }}
              />
              <mesh
                name="tree1-tree_crown_3"
                castShadow
                receiveShadow
                geometry={nodes["tree1-tree_crown_3"].geometry}
                material={nodes["tree1-tree_crown_3"].material}
                userData={{ name: "tree.1-tree crown" }}
              />
            </group>
            <group
              name="tree_18"
              position={[85.4478149, -58.2860909, -12.100378]}
              rotation={[-0.7487556, 0.3555608, -1.6600197]}
              userData={{ name: "tree" }}
            >
              <mesh
                name="tree-tree_trunk_18"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_trunk_18"].geometry}
                material={nodes["tree-tree_trunk_18"].material}
                userData={{ name: "tree-tree trunk" }}
              />
              <mesh
                name="tree-tree_crown_18"
                castShadow
                receiveShadow
                geometry={nodes["tree-tree_crown_18"].geometry}
                material={nodes["tree-tree_crown_18"].material}
                userData={{ name: "tree-tree crown" }}
              />
            </group>
            <group
              name="tree1_4"
              position={[40.9639893, 82.7540054, -17.2018681]}
              rotation={[-1.9420455, -0.9191507, -1.4810436]}
              userData={{ name: "tree.1" }}
            >
              <mesh
                name="tree1-tree_trunk_4"
                castShadow
                receiveShadow
                geometry={nodes["tree1-tree_trunk_4"].geometry}
                material={nodes["tree1-tree_trunk_4"].material}
                userData={{ name: "tree.1-tree trunk" }}
              />
              <mesh
                name="tree1-tree_crown_4"
                castShadow
                receiveShadow
                geometry={nodes["tree1-tree_crown_4"].geometry}
                material={nodes["tree1-tree_crown_4"].material}
                userData={{ name: "tree.1-tree crown" }}
              />
            </group>
          </group>
          <group /* Houses */
            name="houses"
            position={[0, -19.7400742, 13.3222532]}
            rotation={[0, -1e-7, -1e-7]}
            userData={{ name: "houses" }}
            /* scale={2} */
            ref={allHouses}
          >
            <group
              name="house"
              position={[43.7886505, 46.6600456, 88.897934]}
              rotation={[-1.7954383, -0.5447743, -2.5780792]}
              userData={{ name: "house" }}
              ref={__registerRef(1)}
              onPointerOver={(e) => {
                console.log("OVER", state);
                state.current[1]?.triggers.onPointerOver(e, 1);}
              }
              onPointerOut={(e) => state.current[1]?.triggers.onPointerOut(e, 1)}
              onClick={(e) => state.current[1]?.triggers.onClick(e, 1)}
            >
              <mesh
                name="house-walls_house"
                castShadow
                receiveShadow
                geometry={nodes["house-walls_house"].geometry}
                material={nodes["house-walls_house"].material}
                userData={{ name: "house-walls house" }}
              />
              <mesh
                name="house-chimney_house,door"
                castShadow
                receiveShadow
                geometry={nodes["house-chimney_house,door"].geometry}
                material={nodes["house-chimney_house,door"].material}
                userData={{ name: "house-chimney house,door" }}
              />
              <mesh
                name="house-door_house"
                castShadow
                receiveShadow
                geometry={nodes["house-door_house"].geometry}
                material={nodes["house-door_house"].material}
                userData={{ name: "house-door house" }}
              />
              <mesh
                name="house-roof_house"
                castShadow
                receiveShadow
                geometry={nodes["house-roof_house"].geometry}
                material={nodes["house-roof_house"].material}
                userData={{ name: "house-roof house" }}
              />
              <mesh
                name="Cube1"
                castShadow
                receiveShadow
                geometry={nodes.Cube1.geometry}
                material={nodes.Cube1.material}
                position={[0, 10.7414083, 5.4267135]}
                userData={{ name: "Cube.1" }}
              />
            </group>
            <group
              name="house2"
              position={[73.8882446, 83.0963058, -22.3211422]}
              rotation={[-1.9420455, -0.9191507, -1.4810436]}
              userData={{ name: "house.2" }}
              ref={__registerRef(2)}
            >
              <group
                name="door"
                position={[11.6516104, -7.5169234, 0.1860591]}
                userData={{ name: "door" }}
              >
                <mesh
                  name="door-door_house"
                  castShadow
                  receiveShadow
                  geometry={nodes["door-door_house"].geometry}
                  material={nodes["door-door_house"].material}
                  userData={{ name: "door-door house" }}
                />
                <mesh
                  name="door-chimney_house,door"
                  castShadow
                  receiveShadow
                  geometry={nodes["door-chimney_house,door"].geometry}
                  material={nodes["door-chimney_house,door"].material}
                  userData={{ name: "door-chimney house,door" }}
                />
              </group>
              <group
                name="windows"
                position={[-0.0156519, -4.5130849, 0.0122816]}
                rotation={[-1e-7, 1.5705347, 0]}
                userData={{ name: "windows" }}
              >
                <mesh
                  name="windows-door_house"
                  castShadow
                  receiveShadow
                  geometry={nodes["windows-door_house"].geometry}
                  material={nodes["windows-door_house"].material}
                  userData={{ name: "windows-door house" }}
                />
                <mesh
                  name="windows-chimney_house,door"
                  castShadow
                  receiveShadow
                  geometry={nodes["windows-chimney_house,door"].geometry}
                  material={nodes["windows-chimney_house,door"].material}
                  userData={{ name: "windows-chimney house,door" }}
                />
              </group>
              <group
                name="roof"
                position={[5.9592867, 8.8925657, -1e-7]}
                userData={{ name: "roof" }}
              >
                <mesh
                  name="roof-roof_house2"
                  castShadow
                  receiveShadow
                  geometry={nodes["roof-roof_house2"].geometry}
                  material={nodes["roof-roof_house2"].material}
                  userData={{ name: "roof-roof house2" }}
                />
                <mesh
                  name="roof-door_house"
                  castShadow
                  receiveShadow
                  geometry={nodes["roof-door_house"].geometry}
                  material={nodes["roof-door_house"].material}
                  userData={{ name: "roof-door house" }}
                />
              </group>
                <mesh
                  name="house2-walls_house2"
                  castShadow
                  receiveShadow
                  geometry={nodes["house2-walls_house2"].geometry}
                  material={nodes["house2-walls_house2"].material}
                  userData={{ name: "house.2-walls house2" }}
                />
                <mesh
                  name="house2-roof_house2"
                  castShadow
                  receiveShadow
                  geometry={nodes["house2-roof_house2"].geometry}
                  material={nodes["house2-roof_house2"].material}
                  userData={{ name: "house.2-roof house2" }}
                />
                <mesh
                  name="chimney"
                  castShadow
                  receiveShadow
                  geometry={nodes.chimney.geometry}
                  material={nodes.chimney.material}
                  position={[-3.7937169, 11.2482481, 5.4292717]}
                  userData={{ name: "chimney" }}
                />
            </group>
            <group
              name="house5"
              position={[-36.6506004, 68.4233704, -82.1457443]}
              rotation={[-1.0775299, 0.3014015, 0.4602512]}
              userData={{ name: "house.5" }}
              /* ref={(r) => {addHouse(r)}} */
            >
              <group
                name="tree_19"
                position={[0, -3.571974, -24.6608295]}
                userData={{ name: "tree" }}
              >
                <mesh
                  name="tree-tree_crown_19"
                  castShadow
                  receiveShadow
                  geometry={nodes["tree-tree_crown_19"].geometry}
                  material={nodes["tree-tree_crown_19"].material}
                  userData={{ name: "tree-tree crown" }}
                />
                <mesh
                  name="tree-tree_trunk_19"
                  castShadow
                  receiveShadow
                  geometry={nodes["tree-tree_trunk_19"].geometry}
                  material={nodes["tree-tree_trunk_19"].material}
                  userData={{ name: "tree-tree trunk" }}
                />
              </group>
              <group
                name="door_1"
                position={[9.6591854, -6.2315297, 0.154243]}
                userData={{ name: "door" }}
              >
                <mesh
                  name="door-door_house_1"
                  castShadow
                  receiveShadow
                  geometry={nodes["door-door_house_1"].geometry}
                  material={nodes["door-door_house_1"].material}
                  userData={{ name: "door-door house" }}
                />
                <mesh
                  name="door-chimney_house,door_1"
                  castShadow
                  receiveShadow
                  geometry={nodes["door-chimney_house,door_1"].geometry}
                  material={nodes["door-chimney_house,door_1"].material}
                  userData={{ name: "door-chimney house,door" }}
                />
              </group>
              <group
                name="windows_1"
                position={[-0.012975, -3.7413473, 0.0101814]}
                rotation={[0, 1.5705347, 0]}
                userData={{ name: "windows" }}
              >
                <mesh
                  name="windows-door_house_1"
                  castShadow
                  receiveShadow
                  geometry={nodes["windows-door_house_1"].geometry}
                  material={nodes["windows-door_house_1"].material}
                  userData={{ name: "windows-door house" }}
                />
                <mesh
                  name="windows-chimney_house,door_1"
                  castShadow
                  receiveShadow
                  geometry={nodes["windows-chimney_house,door_1"].geometry}
                  material={nodes["windows-chimney_house,door_1"].material}
                  userData={{ name: "windows-chimney house,door" }}
                />
              </group>
              <group
                name="roof_1"
                position={[4.940249, 7.3719368, -1e-7]}
                userData={{ name: "roof" }}
              >
                <mesh
                  name="roof-roof_house2_1"
                  castShadow
                  receiveShadow
                  geometry={nodes["roof-roof_house2_1"].geometry}
                  material={nodes["roof-roof_house2_1"].material}
                  userData={{ name: "roof-roof house2" }}
                />
                <mesh
                  name="roof-door_house_1"
                  castShadow
                  receiveShadow
                  geometry={nodes["roof-door_house_1"].geometry}
                  material={nodes["roof-door_house_1"].material}
                  userData={{ name: "roof-door house" }}
                />
              </group>
              <mesh
                name="house5-walls_house2"
                castShadow
                receiveShadow
                geometry={nodes["house5-walls_house2"].geometry}
                material={nodes["house5-walls_house2"].material}
                userData={{ name: "house.5-walls house2" }}
              />
              <mesh
                name="house5-roof_house2"
                castShadow
                receiveShadow
                geometry={nodes["house5-roof_house2"].geometry}
                material={nodes["house5-roof_house2"].material}
                userData={{ name: "house.5-roof house2" }}
              />
              <mesh
                name="chimney_1"
                castShadow
                receiveShadow
                geometry={nodes.chimney_1.geometry}
                material={nodes.chimney_1.material}
                position={[-3.1449914, 9.3247976, 4.5008664]}
                userData={{ name: "chimney" }}
              />
            </group>
            <group
              name="house1"
              position={[41.6749954, -80.8798294, -44.51651]}
              rotation={[-0.742796, 1.200526, -1.7547974]}
              userData={{ name: "house.1" }}
            >
              <group
                name="door_2"
                position={[11.6516104, -5.8492899, 0.1860591]}
                userData={{ name: "door" }}
              >
                <mesh
                  name="door-door_house_2"
                  castShadow
                  receiveShadow
                  geometry={nodes["door-door_house_2"].geometry}
                  material={nodes["door-door_house_2"].material}
                  userData={{ name: "door-door house" }}
                />
                <mesh
                  name="door-chimney_house,door_2"
                  castShadow
                  receiveShadow
                  geometry={nodes["door-chimney_house,door_2"].geometry}
                  material={nodes["door-chimney_house,door_2"].material}
                  userData={{ name: "door-chimney house,door" }}
                />
              </group>
              <group
                name="windows_2"
                position={[-0.0156519, -2.8454514, 0.0122816]}
                rotation={[0, 1.5705347, 0]}
                userData={{ name: "windows" }}
              >
                <mesh
                  name="windows-door_house_2"
                  castShadow
                  receiveShadow
                  geometry={nodes["windows-door_house_2"].geometry}
                  material={nodes["windows-door_house_2"].material}
                  userData={{ name: "windows-door house" }}
                />
                <mesh
                  name="windows-chimney_house,door_2"
                  castShadow
                  receiveShadow
                  geometry={nodes["windows-chimney_house,door_2"].geometry}
                  material={nodes["windows-chimney_house,door_2"].material}
                  userData={{ name: "windows-chimney house,door" }}
                />
              </group>
              <group
                name="roof_2"
                position={[5.9592867, 10.5601988, -1e-7]}
                userData={{ name: "roof" }}
              >
                <mesh
                  name="roof-roof_house2_2"
                  castShadow
                  receiveShadow
                  geometry={nodes["roof-roof_house2_2"].geometry}
                  material={nodes["roof-roof_house2_2"].material}
                  userData={{ name: "roof-roof house2" }}
                />
                <mesh
                  name="roof-door_house_2"
                  castShadow
                  receiveShadow
                  geometry={nodes["roof-door_house_2"].geometry}
                  material={nodes["roof-door_house_2"].material}
                  userData={{ name: "roof-door house" }}
                />
              </group>
              <mesh
                name="chimney_2"
                castShadow
                receiveShadow
                geometry={nodes.chimney_2.geometry}
                material={nodes.chimney_2.material}
                position={[-3.7937169, 12.9158812, 5.4292717]}
                userData={{ name: "chimney" }}
              />
              <mesh
                name="house1-walls_house2"
                castShadow
                receiveShadow
                geometry={nodes["house1-walls_house2"].geometry}
                material={nodes["house1-walls_house2"].material}
                userData={{ name: "house.1-walls house2" }}
              />
              <mesh
                name="house1-roof_house2"
                castShadow
                receiveShadow
                geometry={nodes["house1-roof_house2"].geometry}
                material={nodes["house1-roof_house2"].material}
                userData={{ name: "house.1-roof house2" }}
              />
            </group>
            <group
              name="house3"
              position={[-39.0989876, 37.7642403, 92.7123795]}
              rotation={[1.3043627, -0.0930607, 0.3963169]}
              userData={{ name: "house.3" }}
            >
              <mesh
                name="house3-chimney_house,door"
                castShadow
                receiveShadow
                geometry={nodes["house3-chimney_house,door"].geometry}
                material={nodes["house3-chimney_house,door"].material}
                userData={{ name: "house.3-chimney house,door" }}
              />
              <mesh
                name="house3-chimney_house,door_1"
                castShadow
                receiveShadow
                geometry={nodes["house3-chimney_house,door_1"].geometry}
                material={nodes["house3-chimney_house,door_1"].material}
                userData={{ name: "house.3-chimney house,door" }}
              />
              <mesh
                name="house3-door_house"
                castShadow
                receiveShadow
                geometry={nodes["house3-door_house"].geometry}
                material={nodes["house3-door_house"].material}
                userData={{ name: "house.3-door house" }}
              />
              <mesh
                name="house3-roof_house"
                castShadow
                receiveShadow
                geometry={nodes["house3-roof_house"].geometry}
                material={nodes["house3-roof_house"].material}
                userData={{ name: "house.3-roof house" }}
              />
              <mesh
                name="house3-walls_house"
                castShadow
                receiveShadow
                geometry={nodes["house3-walls_house"].geometry}
                material={nodes["house3-walls_house"].material}
                userData={{ name: "house.3-walls house" }}
              />
            </group>
            <group
              name="house6"
              position={[103.0159607, -23.3933201, 0.9409122]}
              rotation={[-0.7657917, 0.1666034, -1.6556023]}
              userData={{ name: "house.6" }}
            >
              <mesh
                name="house6-chimney_house,door"
                castShadow
                receiveShadow
                geometry={nodes["house6-chimney_house,door"].geometry}
                material={nodes["house6-chimney_house,door"].material}
                userData={{ name: "house.6-chimney house,door" }}
              />
              <mesh
                name="house6-chimney_house,door_1"
                castShadow
                receiveShadow
                geometry={nodes["house6-chimney_house,door_1"].geometry}
                material={nodes["house6-chimney_house,door_1"].material}
                userData={{ name: "house.6-chimney house,door" }}
              />
              <mesh
                name="house6-door_house"
                castShadow
                receiveShadow
                geometry={nodes["house6-door_house"].geometry}
                material={nodes["house6-door_house"].material}
                userData={{ name: "house.6-door house" }}
              />
              <mesh
                name="house6-roof_house"
                castShadow
                receiveShadow
                geometry={nodes["house6-roof_house"].geometry}
                material={nodes["house6-roof_house"].material}
                userData={{ name: "house.6-roof house" }}
              />
              <mesh
                name="house6-walls_house"
                castShadow
                receiveShadow
                geometry={nodes["house6-walls_house"].geometry}
                material={nodes["house6-walls_house"].material}
                userData={{ name: "house.6-walls house" }}
              />
            </group>
            <group
              name="house4"
              position={[-103.0159683, 10.1508493, -31.8437805]}
              rotation={[-1.9827044, 0.1563828, 1.3966339]}
              userData={{ name: "house.4" }}
            >
              <mesh
                name="house4-chimney_house,door"
                castShadow
                receiveShadow
                geometry={nodes["house4-chimney_house,door"].geometry}
                material={nodes["house4-chimney_house,door"].material}
                userData={{ name: "house.4-chimney house,door" }}
              />
              <mesh
                name="house4-chimney_house,door_1"
                castShadow
                receiveShadow
                geometry={nodes["house4-chimney_house,door_1"].geometry}
                material={nodes["house4-chimney_house,door_1"].material}
                userData={{ name: "house.4-chimney house,door" }}
              />
              <mesh
                name="house4-door_house"
                castShadow
                receiveShadow
                geometry={nodes["house4-door_house"].geometry}
                material={nodes["house4-door_house"].material}
                userData={{ name: "house.4-door house" }}
              />
              <mesh
                name="house4-roof_house"
                castShadow
                receiveShadow
                geometry={nodes["house4-roof_house"].geometry}
                material={nodes["house4-roof_house"].material}
                userData={{ name: "house.4-roof house" }}
              />
              <mesh
                name="house4-walls_house"
                castShadow
                receiveShadow
                geometry={nodes["house4-walls_house"].geometry}
                material={nodes["house4-walls_house"].material}
                userData={{ name: "house.4-walls house" }}
              />
            </group>
            <group
              name="house7"
              position={[-53.8750534, 1.3160462, -96.054184]}
              rotation={[-1.9827043, 0.1563828, 0.4577854]}
              userData={{ name: "house.7" }}
            >
              <mesh
                name="house7-chimney_house,door"
                castShadow
                receiveShadow
                geometry={nodes["house7-chimney_house,door"].geometry}
                material={nodes["house7-chimney_house,door"].material}
                userData={{ name: "house.7-chimney house,door" }}
              />
              <mesh
                name="house7-chimney_house,door_1"
                castShadow
                receiveShadow
                geometry={nodes["house7-chimney_house,door_1"].geometry}
                material={nodes["house7-chimney_house,door_1"].material}
                userData={{ name: "house.7-chimney house,door" }}
              />
              <mesh
                name="house7-door_house"
                castShadow
                receiveShadow
                geometry={nodes["house7-door_house"].geometry}
                material={nodes["house7-door_house"].material}
                userData={{ name: "house.7-door house" }}
              />
              <mesh
                name="house7-roof_house"
                castShadow
                receiveShadow
                geometry={nodes["house7-roof_house"].geometry}
                material={nodes["house7-roof_house"].material}
                userData={{ name: "house.7-roof house" }}
              />
              <mesh
                name="house7-walls_house"
                castShadow
                receiveShadow
                geometry={nodes["house7-walls_house"].geometry}
                material={nodes["house7-walls_house"].material}
                userData={{ name: "house.7-walls house" }}
              />
            </group>
          </group>
          <group /* Buildings */
            name="buildings"
            position={[12.3439198, 26.1792793, -13.3383694]}
            userData={{ name: "buildings" }}
          >
            <group
              name="building01"
              position={[-76.946167, 63.7873268, 52.0564003]}
              rotation={[0.1578147, 0.1100396, 0.6193919]}
              userData={{ name: "building01" }}
            >
              <mesh
                name="building01-chimney_house,door"
                castShadow
                receiveShadow
                geometry={nodes["building01-chimney_house,door"].geometry}
                material={nodes["building01-chimney_house,door"].material}
                userData={{ name: "building01-chimney house,door" }}
              />
              <mesh
                name="building01-water"
                castShadow
                receiveShadow
                geometry={nodes["building01-water"].geometry}
                material={nodes["building01-water"].material}
                userData={{ name: "building01-water" }}
              />
            </group>
            <group
              name="building03"
              position={[-12.0056334, 86.037674, 2.9778636]}
              rotation={[-0.1588395, 0, 0]}
              userData={{ name: "building03" }}
            >
              <mesh
                name="building03-stones"
                castShadow
                receiveShadow
                geometry={nodes["building03-stones"].geometry}
                material={nodes["building03-stones"].material}
                userData={{ name: "building03-stones" }}
              />
              <mesh
                name="building03-water"
                castShadow
                receiveShadow
                geometry={nodes["building03-water"].geometry}
                material={nodes["building03-water"].material}
                userData={{ name: "building03-water" }}
              />
            </group>
            <group
              name="building021"
              position={[-30.6010704, 48.4962196, 96.4433899]}
              rotation={[0.7252609, -0.2895254, 0.1643084]}
              userData={{ name: "building02.1" }}
            >
              <mesh
                name="building021-walls_house2"
                castShadow
                receiveShadow
                geometry={nodes["building021-walls_house2"].geometry}
                material={nodes["building021-walls_house2"].material}
                userData={{ name: "building02.1-walls house2" }}
              />
              <mesh
                name="building021-water"
                castShadow
                receiveShadow
                geometry={nodes["building021-water"].geometry}
                material={nodes["building021-water"].material}
                userData={{ name: "building02.1-water" }}
              />
            </group>
            <group
              name="building02"
              position={[42.8192062, -86.037674, -58.2300987]}
              rotation={[-2.2143335, -0.3537434, -0.5701386]}
              userData={{ name: "building02" }}
            >
              <mesh
                name="building02-water"
                castShadow
                receiveShadow
                geometry={nodes["building02-water"].geometry}
                material={nodes["building02-water"].material}
                userData={{ name: "building02-water" }}
              />
              <mesh
                name="building02-walls_house2"
                castShadow
                receiveShadow
                geometry={nodes["building02-walls_house2"].geometry}
                material={nodes["building02-walls_house2"].material}
                userData={{ name: "building02-walls house2" }}
              />
            </group>
            <group
              name="building03_1"
              position={[76.946167, -18.9448566, -58.8706474]}
              rotation={[-1.8253601, -0.3987314, -0.9909955]}
              userData={{ name: "building03" }}
            >
              <mesh
                name="building03-water_1"
                castShadow
                receiveShadow
                geometry={nodes["building03-water_1"].geometry}
                material={nodes["building03-water_1"].material}
                userData={{ name: "building03-water" }}
              />
              <mesh
                name="building03-stones_1"
                castShadow
                receiveShadow
                geometry={nodes["building03-stones_1"].geometry}
                material={nodes["building03-stones_1"].material}
                userData={{ name: "building03-stones" }}
              />
            </group>
            <group
              name="building011"
              position={[13.3210602, -26.6137733, -96.4433899]}
              rotation={[-1.5537169, -0.6180532, -0.2498461]}
              userData={{ name: "building01.1" }}
            >
              <mesh
                name="building011-water"
                castShadow
                receiveShadow
                geometry={nodes["building011-water"].geometry}
                material={nodes["building011-water"].material}
                userData={{ name: "building01.1-water" }}
              />
              <mesh
                name="building011-chimney_house,door"
                castShadow
                receiveShadow
                geometry={nodes["building011-chimney_house,door"].geometry}
                material={nodes["building011-chimney_house,door"].material}
                userData={{ name: "building01.1-chimney house,door" }}
              />
            </group>
          </group>
          <group /* Stones */
            name="stones"
            position={[22.7955627, -27.0286446, 43.4143639]}
            rotation={[0, -1e-7, -1e-7]}
            userData={{ name: "stones" }}
          >
            <mesh
              name="stones3"
              castShadow
              receiveShadow
              geometry={nodes.stones3.geometry}
              material={nodes.stones3.material}
              position={[66.4814072, 29.6005936, -66.3674011]}
              rotation={[-2.570023, 0.6328218, -0.1968403]}
              userData={{ name: "stones.3" }}
            />
            <mesh
              name="stones_1"
              castShadow
              receiveShadow
              geometry={nodes.stones_1.geometry}
              material={nodes.stones_1.material}
              position={[-37.0126305, -2.0459893, 66.3673935]}
              rotation={[1.0556465, 0.1647632, -2.9460249]}
              userData={{ name: "stones" }}
            />
            <mesh
              name="stones3_1"
              castShadow
              receiveShadow
              geometry={nodes.stones3_1.geometry}
              material={nodes.stones3_1.material}
              position={[9.8920832, -29.6005878, 51.9617271]}
              rotation={[0.2839517, 0, 0.3750816]}
              userData={{ name: "stones.3" }}
            />
            <mesh
              name="stones2"
              castShadow
              receiveShadow
              geometry={nodes.stones2.geometry}
              material={nodes.stones2.material}
              position={[-66.4814148, -28.88484, 43.9576645]}
              rotation={[1.0170635, 0.3486839, -2.9361854]}
              userData={{ name: "stones.2" }}
            />
          </group>
          <group /* Road */
            name="road"
            position={[-3.2462826, -4.4782968, 12.9718542]}
            userData={{ name: "road" }}
          >
            <mesh
              name="road_1"
              castShadow
              receiveShadow
              geometry={nodes.road_1.geometry}
              material={nodes.road_1.material}
              userData={{ name: "road" }}
            />
            <mesh
              name="road-roof_house"
              castShadow
              receiveShadow
              geometry={nodes["road-roof_house"].geometry}
              material={nodes["road-roof_house"].material}
              userData={{ name: "road-roof house" }}
            />
            <mesh
              name="road-background,floor"
              castShadow
              receiveShadow
              geometry={nodes["road-background,floor"].geometry}
              material={materials["background,floor"]}
              userData={{ name: "road-background,floor" }}
            />
          </group>
          <group /* Planet! */
            name="planet"
            position={[-0.4207434, -10.9949427, 10.288579]}
            rotation={[1.0053096, -1e-7, 1e-7]}
            userData={{ name: "planet" }}
          >
            <mesh
              name="planet-planet"
              castShadow
              receiveShadow
              geometry={nodes["planet-planet"].geometry}
              material={materials.planet}
              userData={{ name: "planet-planet" }}
            />
            <mesh
              name="planet-water"
              castShadow
              receiveShadow
              geometry={nodes["planet-water"].geometry}
              material={nodes["planet-water"].material}
              userData={{ name: "planet-water" }}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(defaultLocation);
