/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useMemo } from "react";
import { useGLTF, Merged, PerspectiveCamera } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    body_15_instance_0: THREE.Mesh;
    body_15_instance_1: THREE.Mesh;
    body_16_instance_0: THREE.Mesh;
    body_17_instance_0: THREE.Mesh;
    body_15_instance_2: THREE.Mesh;
    body_15_instance_3: THREE.Mesh;
    body_16_instance_1: THREE.Mesh;
    body_17_instance_1: THREE.Mesh;
    body_14_instance_0: THREE.Mesh;
    body_14_instance_1: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    body_18_instance_0: THREE.Mesh;
    body_19_instance_0: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    Spring_Link__0_Parts_1: THREE.Mesh;
    Spring_Link__0_Parts_1_1: THREE.Mesh;
    Spring_Link__0_Parts_1_2: THREE.Mesh;
    body_18_instance_1: THREE.Mesh;
    body_19_instance_1: THREE.Mesh;
    body_7_instance_0: THREE.Mesh;
    body_7_instance_1: THREE.Mesh;
    body_8: THREE.Mesh;
    body_9: THREE.Mesh;
    body_10: THREE.Mesh;
    body_11: THREE.Mesh;
    body_12: THREE.Mesh;
    body_13_instance_0: THREE.Mesh;
    body_13_instance_1: THREE.Mesh;
    body_instance_2: THREE.Mesh;
    body_instance_3: THREE.Mesh;
    body_1: THREE.Mesh;
    body_2: THREE.Mesh;
    body_3: THREE.Mesh;
    body_4: THREE.Mesh;
    body_5: THREE.Mesh;
    body_6: THREE.Mesh;
    body_20: THREE.Mesh;
    body_21: THREE.Mesh;
    body_22: THREE.Mesh;
    body_23: THREE.Mesh;
    body_24_instance_0: THREE.Mesh;
    ["Piston_123-844_0_Parts_1"]: THREE.Mesh;
    ["Piston_123-844_0_Parts_1_1"]: THREE.Mesh;
    body_24_instance_1: THREE.Mesh;
    ["Piston_123-844_0_Parts_1"]: THREE.Mesh;
    ["Piston_123-844_0_Parts_1_1"]: THREE.Mesh;
    body_instance_0: THREE.Mesh;
    body_instance_1: THREE.Mesh;
    ["Lifter_123-923_0_Parts_1"]: THREE.Mesh;
    ["Lifter_123-923_0_Parts_1_1"]: THREE.Mesh;
    ["Lifter_123-923_0_Parts_1"]: THREE.Mesh;
    ["Lifter_123-923_0_Parts_1_1"]: THREE.Mesh;
    ["Lifter_123-923_0_Parts_1"]: THREE.Mesh;
    ["Lifter_123-923_0_Parts_1_1"]: THREE.Mesh;
    ["Lifter_123-923_0_Parts_1"]: THREE.Mesh;
    ["Lifter_123-923_0_Parts_1_1"]: THREE.Mesh;
    ["rod_123-699_0_Parts_1"]: THREE.Mesh;
    ["rod_123-699_0_Parts_1_1"]: THREE.Mesh;
    ["rod_123-699_0_Parts_1"]: THREE.Mesh;
    ["rod_123-699_0_Parts_1_1"]: THREE.Mesh;
  };
  materials: {
    Material_16: THREE.MeshStandardMaterial;
    Material_20: THREE.MeshStandardMaterial;
    Material_20: THREE.MeshStandardMaterial;
    Material_16: THREE.MeshStandardMaterial;
    Material_17: THREE.MeshStandardMaterial;
    Material_18: THREE.MeshStandardMaterial;
    Material_23: THREE.MeshStandardMaterial;
    Material_16: THREE.MeshStandardMaterial;
    Material_16: THREE.MeshStandardMaterial;
    Material_16: THREE.MeshStandardMaterial;
    Material_20: THREE.MeshStandardMaterial;
    Material_17: THREE.MeshStandardMaterial;
    Material_17: THREE.MeshStandardMaterial;
    Material_20: THREE.MeshStandardMaterial;
    Material_23: THREE.MeshStandardMaterial;
    Material_17: THREE.MeshStandardMaterial;
    Material_16: THREE.MeshStandardMaterial;
    Material_20: THREE.MeshStandardMaterial;
    Material_20: THREE.MeshStandardMaterial;
    Material_20: THREE.MeshStandardMaterial;
    Material_20: THREE.MeshStandardMaterial;
    Material_23: THREE.MeshStandardMaterial;
    Material_22: THREE.MeshStandardMaterial;
    Material_22: THREE.MeshStandardMaterial;
    Material_17: THREE.MeshStandardMaterial;
    Material_22: THREE.MeshStandardMaterial;
    Material_17: THREE.MeshStandardMaterial;
    Material_17: THREE.MeshStandardMaterial;
    Material_20: THREE.MeshStandardMaterial;
    Material_21: THREE.MeshStandardMaterial;
    Material_17: THREE.MeshStandardMaterial;
    Material_18: THREE.MeshStandardMaterial;
    Material_19: THREE.MeshStandardMaterial;
    Material_20: THREE.MeshStandardMaterial;
  };
};

const resourceLocation = "src/assets/glTF-Sample-Models/2.0/2CylinderEngine/glTF-Embedded/2CylinderEngine.gltf";

export default function InstancedModel(props) {
  const { nodes } = useGLTF(resourceLocation) as GLTFResult;
  const instances = useMemo(
    () => ({
      Bodyinstance: nodes.body_15_instance_0,
      Bodyinstance1: nodes.body_16_instance_0,
      Bodyinstance2: nodes.body_17_instance_0,
      Bodyinstance3: nodes.body_14_instance_0,
      SpringLinkParts: nodes.Spring_Link__0_Parts_1,
      SpringLinkParts1: nodes.Spring_Link__0_Parts_1_1,
      SpringLinkParts2: nodes.Spring_Link__0_Parts_1_2,
      Bodyinstance4: nodes.body_18_instance_0,
      Bodyinstance5: nodes.body_19_instance_0,
      Bodyinstance6: nodes.body_7_instance_0,
      Body: nodes.body_8,
      Body1: nodes.body_9,
      Body2: nodes.body_10,
      Body3: nodes.body_11,
      Body4: nodes.body_12,
      Bodyinstance7: nodes.body_13_instance_0,
      Bodyinstance8: nodes.body_instance_2,
      Body5: nodes.body_1,
      Body6: nodes.body_2,
      Body7: nodes.body_3,
      Body8: nodes.body_4,
      Body9: nodes.body_5,
      Body10: nodes.body_6,
      Body11: nodes.body_20,
      Body12: nodes.body_21,
      Body13: nodes.body_22,
      Body14: nodes.body_23,
      Bodyinstance9: nodes.body_24_instance_0,
      PistonParts: nodes["Piston_123-844_0_Parts_1"],
      PistonParts1: nodes["Piston_123-844_0_Parts_1_1"],
      LifterParts: nodes["Lifter_123-923_0_Parts_1"],
      LifterParts1: nodes["Lifter_123-923_0_Parts_1_1"],
      RodParts: nodes["rod_123-699_0_Parts_1"],
      RodParts1: nodes["rod_123-699_0_Parts_1_1"],
    }),
    [nodes]
  );
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <Model instances={instances} />}
    </Merged>
  );
}

function Model({ instances, ...props }: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(resourceLocation) as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group>
          <group>
            <group
              position={[-48.26182556, -59.11042404, 34.59598541]}
              rotation={[-1.57079492, -2.4e-7, Math.PI / 2]}
            >
              <group
                position={[-0.13409001, -12.99998856, 0.123657]}
                rotation={[0, 0.00227107, 0]}
                scale={[1.00000002, 1, 1.00000002]}
              >
                <group>
                  <instances.Bodyinstance
                    name="body_15_instance_0"
                    position={[18.20175934, 326.73812866, 297.67703247]}
                    rotation={[-Math.PI / 2, 0, 0.05577088]}
                    scale={[1.00000001, 1.00000001, 1]}
                  />
                  <instances.Bodyinstance
                    name="body_15_instance_1"
                    position={[68.16710663, 326.73812866, 297.78866577]}
                    rotation={[-Math.PI / 2, 0, 0.05560667]}
                    scale={[0.99999998, 0.99999998, 1]}
                  />
                  <instances.Bodyinstance1
                    name="body_16_instance_0"
                    position={[49.47110367, 257.12295532, 94.59931183]}
                    rotation={[Math.PI, 0.00227, 0]}
                    scale={[1.00000001, 1, 1.00000001]}
                  />
                  <instances.Bodyinstance2
                    name="body_17_instance_0"
                    position={[49.50515366, 344.35336304, 79.59934998]}
                    rotation={[0, -0.00227005, 0]}
                    scale={[1.00000001, 1, 1.00000001]}
                  />
                </group>
                <group position={[-0.000008, -0.000011, -99.99953461]}>
                  <instances.Bodyinstance
                    name="body_15_instance_2"
                    position={[17.57496071, 326.73812866, 297.62918091]}
                    rotation={[-Math.PI / 2, 0, 0.05171702]}
                    scale={[0.99999998, 0.99999998, 1]}
                  />
                  <instances.Bodyinstance
                    name="body_15_instance_3"
                    position={[67.53964233, 326.73812866, 297.74066162]}
                    rotation={[-Math.PI / 2, 0, 0.05154882]}
                  />
                  <instances.Bodyinstance1
                    name="body_16_instance_1"
                    position={[49.69811249, 257.12298584, 94.59911346]}
                    rotation={[Math.PI, 0.00227, 0]}
                    scale={[1.00000001, 1, 1.00000001]}
                  />
                  <instances.Bodyinstance2
                    name="body_17_instance_1"
                    position={[49.73216629, 344.35336304, 79.59915161]}
                    rotation={[0, -0.00227005, 0]}
                    scale={[1.00000001, 1, 1.00000001]}
                  />
                </group>
                <instances.Bodyinstance3
                  name="body_14_instance_0"
                  position={[48.79470825, 768.67718506, -20.40250397]}
                  rotation={[-3.6e-7, -0.00227, -3.13661946]}
                  scale={[0.99999998, 1.00000003, 1.00000001]}
                />
                <instances.Bodyinstance3
                  name="body_14_instance_1"
                  position={[-29.98022842, 768.69921875, -20.58132744]}
                  rotation={[-9.1e-7, -0.00227, -3.13710523]}
                  scale={[1.00000001, 1, 1.00000001]}
                />
              </group>
              <group
                position={[91.87051392, 80.6325531, 166.26089478]}
                rotation={[0.64567693, -0.19353644, 1.08904427]}
                scale={[0.99999998, 1.00000002, 0.99999998]}
              >
                <group>
                  <group
                    name="_instance_0"
                    position={[141.07516479, 91.42301941, -331.46322632]}
                    rotation={[2.01979456, -0.26470672, 2.36624604]}
                    scale={[0.99999999, 1.00000001, 0.99999998]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_1"
                    position={[-52.27817535, 76.44441223, -179.62875366]}
                    rotation={[-1.12179791, 0.26470656, 0.46642805]}
                    scale={[1.00000001, 0.99999999, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_2"
                    position={[134.79489136, 90.93650055, -326.53158569]}
                    rotation={[2.01979456, -0.26470672, 2.36624604]}
                    scale={[0.99999999, 1.00000001, 0.99999998]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_3"
                    position={[-58.55844116, 75.95790863, -174.69706726]}
                    rotation={[-1.12179791, 0.26470656, 0.46642805]}
                    scale={[1.00000001, 0.99999999, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_4"
                    position={[128.51461792, 90.44998932, -321.59991455]}
                    rotation={[2.01979456, -0.26470672, 2.36624604]}
                    scale={[0.99999999, 1.00000001, 0.99999998]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_5"
                    position={[-64.83870697, 75.4713974, -169.7653656]}
                    rotation={[-1.12179791, 0.26470656, 0.46642805]}
                    scale={[1.00000001, 0.99999999, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_6"
                    position={[122.234375, 89.96346283, -316.66821289]}
                    rotation={[2.01979456, -0.26470672, 2.36624604]}
                    scale={[0.99999999, 1.00000001, 0.99999998]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_7"
                    position={[-71.11894989, 74.98487091, -164.8336792]}
                    rotation={[-1.12179791, 0.26470656, 0.46642805]}
                    scale={[1.00000001, 0.99999999, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_8"
                    position={[115.95410156, 89.47693634, -311.7364502]}
                    rotation={[2.01979456, -0.26470672, 2.36624604]}
                    scale={[0.99999999, 1.00000001, 0.99999998]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_9"
                    position={[-77.3992157, 74.49835205, -159.9019928]}
                    rotation={[-1.12179791, 0.26470656, 0.46642805]}
                    scale={[1.00000001, 0.99999999, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                </group>
                <instances.Bodyinstance4
                  name="body_18_instance_0"
                  position={[45.59693909, 243.51312256, 69.38878632]}
                  rotation={[-2.23672996, -0.49980567, 0.46360881]}
                  scale={[1.00000003, 0.99999999, 0.99999999]}
                />
                <instances.Bodyinstance5
                  name="body_19_instance_0"
                  position={[-1.24852002, -250.06192017, -90.2271347]}
                  rotation={[-0.18006295, 0.64904577, 0.17106725]}
                  scale={[0.99999998, 0.99999998, 1.00000003]}
                />
              </group>
              <group
                position={[14.89819336, 85.82951355, -48.03464508]}
                rotation={[2.49591549, 0.19353636, -2.05254815]}
                scale={[1, 1.00000001, 0.99999998]}
              >
                <group>
                  <group
                    name="_instance_10"
                    position={[141.37188721, 88.10767365, -327.10848999]}
                    rotation={[2.00687666, -0.25574687, 2.40173916]}
                    scale={[1.00000001, 1.00000001, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_11"
                    position={[-55.24869537, 72.87601471, -172.70831299]}
                    rotation={[-1.13471551, 0.25574685, 0.50856939]}
                    scale={[1, 1.00000002, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_12"
                    position={[136.66165161, 87.74280548, -323.40975952]}
                    rotation={[2.00687666, -0.25574687, 2.40173916]}
                    scale={[1.00000001, 1.00000001, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_13"
                    position={[-59.95888519, 72.51113129, -169.009552]}
                    rotation={[-1.13471551, 0.25574685, 0.50856939]}
                    scale={[1, 1.00000002, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_14"
                    position={[131.95153809, 87.37792206, -319.71096802]}
                    rotation={[2.00687666, -0.25574687, 2.40173916]}
                    scale={[1.00000001, 1.00000001, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_15"
                    position={[-64.66907501, 72.14624786, -165.31079102]}
                    rotation={[-1.13471551, 0.25574685, 0.50856939]}
                    scale={[1, 1.00000002, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_16"
                    position={[127.24127197, 87.01302338, -316.01217651]}
                    rotation={[2.00687666, -0.25574687, 2.40173916]}
                    scale={[1.00000001, 1.00000001, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_17"
                    position={[-69.37929535, 71.78133392, -161.61203003]}
                    rotation={[-1.13471551, 0.25574685, 0.50856939]}
                    scale={[1, 1.00000002, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_18"
                    position={[122.53109741, 86.64814758, -312.31338501]}
                    rotation={[2.00687666, -0.25574687, 2.40173916]}
                    scale={[1.00000001, 1.00000001, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                  <group
                    name="_instance_19"
                    position={[-74.08947754, 71.41646576, -157.91323853]}
                    rotation={[-1.13471551, 0.25574685, 0.50856939]}
                    scale={[1, 1.00000002, 1.00000002]}
                  >
                    <instances.SpringLinkParts name="Spring_Link__0_Parts_1" />
                    <instances.SpringLinkParts1 name="Spring_Link__0_Parts_1_1" />
                    <instances.SpringLinkParts2 name="Spring_Link__0_Parts_1_2" />
                  </group>
                </group>
                <instances.Bodyinstance4
                  name="body_18_instance_1"
                  position={[34.1871376, 252.66601563, 65.06369019]}
                  rotation={[-2.2880533, -0.52149734, 0.43851852]}
                  scale={[0.99999999, 1.00000001, 1.00000003]}
                />
                <instances.Bodyinstance5
                  name="body_19_instance_1"
                  position={[-5.7467351, -250.40991211, -86.68790436]}
                  rotation={[-0.18006295, 0.64904577, 0.17106725]}
                  scale={[0.99999998, 0.99999998, 1.00000003]}
                />
              </group>
              <instances.Bodyinstance6
                name="body_7_instance_0"
                position={[-23.12494469, 247.73817444, 220.354599]}
                rotation={[-Math.PI / 2, 0, 0.00449802]}
                scale={[0.99999998, 0.99999998, 1]}
              />
              <instances.Bodyinstance6
                name="body_7_instance_1"
                position={[81.19497681, 247.73817444, 220.14607239]}
                rotation={[-Math.PI / 2, 0, -0.00365401]}
              />
              <instances.Body
                name="body_8"
                position={[49.58733749, 175.7381897, 89.59835815]}
                rotation={[Math.PI / 2, 0, 0]}
              />
              <instances.Body1
                name="body_9"
                position={[277.7611084, 580.08062744, -5.38985395]}
                rotation={[0, 0, 0.4449557]}
              />
              <instances.Body2
                name="body_10"
                position={[353.9793396, 330.90402222, -5.3899312]}
                rotation={[0, 0, -0.44495557]}
              />
              <instances.Body3
                name="body_11"
                position={[24.52630043, 213.73817444, 283.07357788]}
                rotation={[-Math.PI / 2, 0, 0]}
              />
              <instances.Body4
                name="body_12"
                position={[51.08792877, 325.73840332, 91.09835815]}
                rotation={[Math.PI / 2, -0.000061, -0.000001]}
              />
              <instances.Bodyinstance7
                name="body_13_instance_0"
                position={[-270.79406738, 145.43400574, 122.04411316]}
                rotation={[Math.PI / 2, 0.43633228, 2.70513303]}
                scale={[0.99999998, 0.99999999, 1.00000002]}
              />
              <instances.Bodyinstance7
                name="body_13_instance_1"
                position={[-141.64085388, 388.67276001, 122.00779724]}
                rotation={[Math.PI / 2, -0.43633327, 2.70525936]}
                scale={1.00000002}
              />
            </group>
            <instances.Bodyinstance8
              name="body_instance_2"
              position={[-295, 21.60527802, -105.32867432]}
              rotation={[-3.13923615, -Math.PI / 2, 0]}
              scale={[0.99999998, 0.99999998, 1]}
            />
            <instances.Bodyinstance8
              name="body_instance_3"
              position={[-295, 21.49887657, 0.49255699]}
              rotation={[3.14066752, -Math.PI / 2, 0]}
              scale={[1.00000001, 1.00000001, 1]}
            />
            <instances.Body5 name="body_1" />
            <instances.Body6
              name="body_2"
              position={[126.93566132, -0.000053, -36.55884933]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <instances.Body7
              name="body_3"
              position={[-126.93566132, 0.000003, 36.55884171]}
              rotation={[Math.PI / 2, 0, Math.PI]}
            />
            <instances.Body8
              name="body_4"
              position={[223.99998474, 30.48792458, 25.00873184]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <instances.Body9
              name="body_5"
              position={[223.99998474, 31.98792839, 23.50873375]}
              rotation={[0, Math.PI / 2, 0]}
            />
            <instances.Body10
              name="body_6"
              position={[65, 128.71702576, -3.27052402]}
              rotation={[-2.35619394, -Math.PI / 2, 0]}
              scale={[1.00000003, 1.00000003, 1]}
            />
          </group>
          <group
            position={[47.17867661, -52.82132721, -88.94477081]}
            rotation={[0, 0, -Math.PI / 4]}
            scale={[0.99999998, 0.99999998, 1]}
          >
            <instances.Body11
              name="body_20"
              position={[-30.29589844, -52.56131363, 25.05522728]}
              rotation={[Math.PI / 2, -0.43720545, Math.PI / 2]}
              scale={[1, 1.00000001, 1.00000001]}
            />
            <instances.Body12
              name="body_21"
              position={[-90.59386444, -24.37981796, -40.05522919]}
              rotation={[-Math.PI, 0, 2.00800079]}
              scale={[1.00000001, 1.00000001, 1]}
            />
          </group>
          <group
            position={[18.09818459, -69.69783783, -105.55981445]}
            rotation={[0, 0, -2.09439511]}
            scale={[0.99999999, 0.99999999, 1]}
          >
            <instances.Body13
              name="body_22"
              position={[-51.31101227, -50.52240753, 107.55981445]}
              rotation={[0, 0, 2.79078136]}
              scale={[0.99999997, 0.99999997, 1]}
            />
            <instances.Body14
              name="body_23"
              position={[-51.31101227, -50.52240753, -18.44018555]}
              rotation={[0, 0, 2.79078136]}
              scale={[0.99999997, 0.99999997, 1]}
            />
          </group>
          <group
            position={[-136.86010742, 64.45372009, 3.8203671]}
            rotation={[0, 0, Math.PI]}
          >
            <instances.Bodyinstance9
              name="body_24_instance_0"
              position={[-45.31546021, -24.61726379, -26.32036781]}
              rotation={[0, 0, 0.02949746]}
              scale={[1.00000002, 1.00000002, 1]}
            />
            <group
              name="_instance_0"
              position={[-294.67718506, 73.97987366, 16.17963219]}
              rotation={[0, 0, Math.PI]}
            >
              <instances.PistonParts name="Piston_123-844_0_Parts_1" />
              <instances.PistonParts1 name="Piston_123-844_0_Parts_1_1" />
            </group>
          </group>
          <group position={[136.86010742, -64.45372009, -36.17963028]}>
            <instances.Bodyinstance9
              name="body_24_instance_1"
              position={[-45.31546021, -24.61726379, -26.32036972]}
              rotation={[0, 0, 0.02949746]}
              scale={[1.00000002, 1.00000002, 1]}
            />
            <group
              name="_instance_1"
              position={[-294.67718506, 73.97987366, 16.17963219]}
              rotation={[0, 0, Math.PI]}
            >
              <instances.PistonParts name="Piston_123-844_0_Parts_1" />
              <instances.PistonParts1 name="Piston_123-844_0_Parts_1_1" />
            </group>
          </group>
          <instances.Bodyinstance8
            name="body_instance_0"
            position={[-295, 132.13952637, -3.98334599]}
            rotation={[-3.13923615, -Math.PI / 2, 0]}
            scale={[0.99999998, 0.99999998, 1]}
          />
          <instances.Bodyinstance8
            name="body_instance_1"
            position={[-295, 123.80779266, -100.10150146]}
            rotation={[-3.13923615, -Math.PI / 2, 0]}
            scale={[0.99999998, 0.99999998, 1]}
          />
          <group
            name="_instance_0"
            position={[100, -133.84883118, 54.37212372]}
            rotation={[Math.PI, Math.PI / 2, 0]}
          >
            <instances.LifterParts name="Lifter_123-923_0_Parts_1" />
            <instances.LifterParts1 name="Lifter_123-923_0_Parts_1_1" />
          </group>
          <group
            name="_instance_1"
            position={[100, -133.84883118, 34.37212753]}
            rotation={[Math.PI, Math.PI / 2, 0]}
          >
            <instances.LifterParts name="Lifter_123-923_0_Parts_1" />
            <instances.LifterParts1 name="Lifter_123-923_0_Parts_1_1" />
          </group>
          <group
            name="_instance_2"
            position={[-100, -66.15116882, 14.37209892]}
            rotation={[0, -Math.PI / 2, 0]}
          >
            <instances.LifterParts name="Lifter_123-923_0_Parts_1" />
            <instances.LifterParts1 name="Lifter_123-923_0_Parts_1_1" />
          </group>
          <group
            name="_instance_3"
            position={[-100, -66.15117645, -5.62789679]}
            rotation={[0, -Math.PI / 2, 0]}
          >
            <instances.LifterParts name="Lifter_123-923_0_Parts_1" />
            <instances.LifterParts1 name="Lifter_123-923_0_Parts_1_1" />
          </group>
          <group
            name="_instance_0"
            position={[71.01806641, 22.19301414, 22]}
            rotation={[0, 0, -0.16690466]}
            scale={[0.99999999, 0.99999999, 1]}
          >
            <instances.RodParts name="rod_123-699_0_Parts_1" />
            <instances.RodParts1 name="rod_123-699_0_Parts_1_1" />
          </group>
          <group
            name="_instance_1"
            position={[-71.01806641, -22.19301224, -20]}
            rotation={[0, 0, 2.97468808]}
            scale={[0.99999998, 0.99999998, 1]}
          >
            <instances.RodParts name="rod_123-699_0_Parts_1" />
            <instances.RodParts1 name="rod_123-699_0_Parts_1_1" />
          </group>
        </group>
        <PerspectiveCamera
          makeDefault={false}
          far={1000000}
          near={0.05}
          fov={18.01072048}
          position={[1005.98742676, 766.31707764, 953.34558105]}
          rotation={[-0.64350099, 0.67474113, 0.43814878]}
          scale={[1.00000003, 1.00000001, 0.99999999]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(resourceLocation);
